/**
 * contentLibrary.js
 * ─────────────────────────────────────────────────────────────
 * Static pool of 40+ practice exercises used as:
 *  1. Fallback when DeepSeek AI is unavailable
 *  2. Seed content for beginner users
 */

// ── READING / ALPHABET ───────────────────────────────────────
export const READING_EXERCISES = [
  { id:'r-001', type:'alphabet', difficulty:'easy', topic:'vowels',
    prompt:'Which of these is a vowel sound?',
    options:['b','p','i','t'], answer:'i', hint:'Vowels are: a, e, i, o, u' },
  { id:'r-002', type:'alphabet', difficulty:'easy', topic:'letters',
    prompt:'Which letter comes after "H" in the alphabet?',
    options:['G','I','J','K'], answer:'I' },
  { id:'r-003', type:'alphabet', difficulty:'easy', topic:'dyslexia',
    prompt:'Which letter sounds like "dee"?',
    options:['b','p','d','q'], answer:'d', hint:'Think of the word "dog"' },
  { id:'r-004', type:'alphabet', difficulty:'easy', topic:'dyslexia',
    prompt:'Which letter sounds like "bee"?',
    options:['d','q','b','p'], answer:'b', hint:'Think of the word "ball"' },
  { id:'r-005', type:'sentence', difficulty:'medium', topic:'grammar',
    prompt:'Choose the correct sentence:',
    options:['She go to school.','She goes to school.','She going to school.','She gone to school.'],
    answer:'She goes to school.' },
  { id:'r-006', type:'sentence', difficulty:'medium', topic:'tense',
    prompt:'Fill in the blank: "Yesterday, he ___ to the park."',
    options:['go','goes','went','going'], answer:'went' },
  { id:'r-007', type:'sentence', difficulty:'medium', topic:'comprehension',
    passage:'Anna loves to paint. Every weekend she visits the park with her sketchbook.',
    prompt:'What does Anna do at the park?',
    options:['She plays football','She reads books','She paints and sketches','She feeds birds'],
    answer:'She paints and sketches' },
  { id:'r-008', type:'comprehension', difficulty:'hard', topic:'inference',
    passage:'Despite the storm warning, the sailors set out to sea. They had a cargo to deliver.',
    prompt:'Why did the sailors go to sea despite the warning?',
    options:['They liked storms','They needed to deliver cargo','The warning was wrong','The sea was calm'],
    answer:'They needed to deliver cargo' },
  { id:'r-009', type:'comprehension', difficulty:'hard', topic:'vocabulary',
    prompt:'"The statesman was known for his eloquent speeches." What does "eloquent" mean?',
    options:['Boring and dull','Well-spoken and expressive','Short and simple','Loud and angry'],
    answer:'Well-spoken and expressive' },
  { id:'r-010', type:'sentence', difficulty:'hard', topic:'grammar',
    prompt:'Which sentence is in the passive voice?',
    options:['She wrote the letter.','The letter was written by her.','She will write.','Writing takes time.'],
    answer:'The letter was written by her.' },
  { id:'r-011', type:'comprehension', difficulty:'hard', topic:'main_idea',
    passage:'Electric cars produce no direct emissions. However, the electricity used to charge them is often generated by fossil fuels.',
    prompt:'What is the main idea of this passage?',
    options:['Electric cars are expensive','Electric cars have benefits but also indirect drawbacks','Fossil fuels are good','Air pollution is increasing'],
    answer:'Electric cars have benefits but also indirect drawbacks' },
];

// ── PHONICS / SPEECH ─────────────────────────────────────────
export const PHONICS_EXERCISES = [
  { id:'ph-001', type:'phonics', difficulty:'easy', topic:'rhyme',
    prompt:'Which word rhymes with "cat"?',
    options:['dog','hat','sun','big'], answer:'hat' },
  { id:'ph-002', type:'phonics', difficulty:'easy', topic:'sound',
    prompt:'Which word starts with the "sss" sound?',
    options:['cat','sun','bat','top'], answer:'sun' },
  { id:'ph-003', type:'phonics', difficulty:'easy', topic:'ending',
    prompt:'Which word ends with the "k" sound?',
    options:['tree','drum','book','ball'], answer:'book' },
  { id:'ph-004', type:'phonics', difficulty:'easy', topic:'ph_sound',
    prompt:'What sound does "phone" start with?',
    options:['p as in pig','f as in fish','b as in bat','v as in van'],
    answer:'f as in fish', hint:'"ph" makes the "f" sound' },
  { id:'ph-005', type:'phonics', difficulty:'easy', topic:'syllables',
    prompt:'How many syllables does "apple" have?',
    options:['1','2','3','4'], answer:'2' },
  { id:'ph-006', type:'phonics', difficulty:'medium', topic:'blend',
    prompt:'What blend do you hear at the start of "frog"?',
    options:['fl','fr','cr','dr'], answer:'fr' },
  { id:'ph-007', type:'phonics', difficulty:'medium', topic:'digraph',
    prompt:'The letters "ch" make what sound?',
    options:['k sound','sh sound','ch sound as in chip','c sound'], answer:'ch sound as in chip' },
  { id:'ph-008', type:'phonics', difficulty:'medium', topic:'silent_letter',
    prompt:'Which word has a silent letter?',
    options:['jump','know','frog','ship'], answer:'know', hint:'The "k" in "know" is silent' },
  { id:'ph-009', type:'phonics', difficulty:'medium', topic:'long_vowel',
    prompt:'Which word has a long "a" sound?',
    options:['cat','hat','cake','lap'], answer:'cake' },
  { id:'ph-010', type:'phonics', difficulty:'medium', topic:'syllables',
    prompt:'How many syllables does "elephant" have?',
    options:['2','3','4','1'], answer:'3' },
  { id:'ph-011', type:'phonics', difficulty:'hard', topic:'vowel_team',
    prompt:'In the word "boat", what vowel team makes the long "o" sound?',
    options:['b-o','o-a','a-t','b-a'], answer:'o-a' },
  { id:'ph-012', type:'phonics', difficulty:'hard', topic:'syllable_split',
    prompt:'How do you split "unhappy" into syllables?',
    options:['un-hap-py','u-nha-ppy','unh-ap-py','un-happy'], answer:'un-hap-py' },
  { id:'ph-013', type:'phonics', difficulty:'hard', topic:'schwa',
    prompt:'The unstressed vowel sound in "alone" is called:',
    options:['long vowel','short vowel','schwa','silent vowel'], answer:'schwa' },
];

// ── VOCABULARY / GAMES ────────────────────────────────────────
export const VOCABULARY_EXERCISES = [
  { id:'v-001', type:'vocabulary', difficulty:'easy', topic:'antonym',
    prompt:'What is the opposite of "hot"?',
    options:['warm','cool','cold','nice'], answer:'cold' },
  { id:'v-002', type:'vocabulary', difficulty:'easy', topic:'synonym',
    prompt:'Which word means the same as "happy"?',
    options:['sad','joyful','angry','tired'], answer:'joyful' },
  { id:'v-003', type:'vocabulary', difficulty:'easy', topic:'definition',
    prompt:'What does "big" mean?',
    options:['small','tiny','large','fast'], answer:'large' },
  { id:'v-004', type:'vocabulary', difficulty:'easy', topic:'category',
    prompt:'Which of these is an animal?',
    options:['table','elephant','pencil','cloud'], answer:'elephant' },
  { id:'v-005', type:'vocabulary', difficulty:'easy', topic:'category',
    prompt:'Which of these is a colour?',
    options:['run','jump','blue','eat'], answer:'blue' },
  { id:'v-006', type:'vocabulary', difficulty:'medium', topic:'context',
    prompt:'"She was exhausted after the marathon." What does "exhausted" mean?',
    options:['excited','very tired','very fast','very happy'], answer:'very tired' },
  { id:'v-007', type:'vocabulary', difficulty:'medium', topic:'synonym',
    prompt:'Which word means the same as "enormous"?',
    options:['tiny','huge','fast','quiet'], answer:'huge' },
  { id:'v-008', type:'vocabulary', difficulty:'medium', topic:'antonym',
    prompt:'What is the opposite of "ancient"?',
    options:['old','modern','large','slow'], answer:'modern' },
  { id:'v-009', type:'vocabulary', difficulty:'medium', topic:'definition',
    prompt:'What does "transparent" mean?',
    options:['dark and solid','you can see through it','very loud','very fast'],
    answer:'you can see through it' },
  { id:'v-010', type:'vocabulary', difficulty:'medium', topic:'word_family',
    prompt:'Which word belongs to the same family as "teach"?',
    options:['learn','teacher','student','school'], answer:'teacher' },
  { id:'v-011', type:'vocabulary', difficulty:'hard', topic:'advanced',
    prompt:'"The politician was known for being magnanimous." What does this mean?',
    options:['mean and petty','very generous and forgiving','extremely clever','loud and arrogant'],
    answer:'very generous and forgiving' },
  { id:'v-012', type:'vocabulary', difficulty:'hard', topic:'prefix',
    prompt:'The prefix "mis-" in "misunderstand" means:',
    options:['again','wrongly','before','not enough'], answer:'wrongly' },
  { id:'v-013', type:'vocabulary', difficulty:'hard', topic:'suffix',
    prompt:'The suffix "-ology" in "biology" means:',
    options:['fear of','study of','love of','full of'], answer:'study of' },
  { id:'v-014', type:'vocabulary', difficulty:'hard', topic:'idiom',
    prompt:'"Break a leg!" is an idiom that means:',
    options:['Be careful','Good luck','Hurry up','Stop talking'], answer:'Good luck' },
];

// ── MASTER INDEX ──────────────────────────────────────────────
export const CONTENT_LIBRARY = {
  reading:    READING_EXERCISES,
  phonics:    PHONICS_EXERCISES,
  vocabulary: VOCABULARY_EXERCISES,
};

/**
 * Gets a random exercise filtered by type and difficulty, excluding seen IDs.
 */
export function getStaticExercise(type, difficulty, seenIds = []) {
  const pool = (CONTENT_LIBRARY[type] || READING_EXERCISES)
    .filter(e => e.difficulty === difficulty && !seenIds.includes(e.id));

  if (!pool.length) {
    const allPool = (CONTENT_LIBRARY[type] || READING_EXERCISES)
      .filter(e => !seenIds.includes(e.id));
    if (!allPool.length) return null;
    return allPool[Math.floor(Math.random() * allPool.length)];
  }
  return pool[Math.floor(Math.random() * pool.length)];
}

/**
 * Maps user skill + learning rate to exercise difficulty.
 */
export function mapToDifficulty(skillLevel, learningRate) {
  if (skillLevel === 'beginner') {
    return learningRate === 'fast' ? 'medium' : 'easy';
  }
  if (skillLevel === 'intermediate') {
    if (learningRate === 'slow') return 'easy';
    if (learningRate === 'fast') return 'hard';
    return 'medium';
  }
  return learningRate === 'slow' ? 'medium' : 'hard';
}
